# Site settings
title: Florian D. Schneider
subtitle: "Dr. rer. nat."

description: > # this means to ignore newlines until "baseurl:"
  I am an ecologist and environmental scientist working on biodiversity valuation and ecological complexity.  Currently I am a freelance researcher and developer and a research associate at Technische Universität Darmstadt.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fdschneider.github.io" # the base hostname & protocol for your site
relative_permalinks: false

keywords: ecology, biodiversity, computational science, functional traits, ecological informatics, ecological networks, neonicotinoids, insect decline

include: ["_assets", "_publications", "_pages"]

social:
  twitter: f_d_schneider
  github: fdschneider
  medium: fdschneider
  instagram: fdschn
  researchgate: Florian_Schneider12
  orcid: 0000-0002-1494-5684

avatar: "_assets/schnecke_cut.jpg"
disqus_short_name : fdschneider

contacts:
  email: florian.dirk.schneider@gmail.com
  postal:
    address1:
    address2:
    street:
    zip: 64285
    city: Darmstadt
    country: GERMANY
  phone:
  pubkey:

cv_file:
publist_file:
tags: theoretical ecology, food webs, biodiversity, science policy, traits, allometry

# Build settings
markdown: kramdown
