# Site settings
title: Florian D. Schneider
subtitle: The simplicity of complex things

description: > # this means to ignore newlines until "baseurl:"
  I am an interdisciplinary environmental scientist working on biodiversity and ecological complexity. Currently I am research associate at Technische Universität Darmstadt, Institute of Linguistics and Literary Studies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fdschneider.github.io" # the base hostname & protocol for your site
relative_permalinks: false

keywords: ecology, biodiversity, computational science, functional traits,  ecological networks, neonicotinoids, insect decline

include: ["_assets", "_publications", "_pages"]

social:
  twitter: f_d_schneider
  github: fdschneider
  medium: fdschneider
  instagram: fdschn
  researchgate: Florian_Schneider12

avatar: "_assets/schnecke_cut.jpg"
disqus_short_name : fdschneider

contacts:
  email: florian.dirk.schneider@gmail.com
  postal:
    address1:
    address2:
    street:
    zip: 64285
    city: Darmstadt
    country: GERMANY
  phone:
  pubkey:

cv_file:
publist_file:
tags: theoretical ecology, food webs, biodiversity, science policy

# Build settings
markdown: kramdown
